--Military overrides
--NDefines.NEconomy.
NDefines.NEconomy.LAND_TECH_MERC_MAINTENANCE_IMPACT = 0.03
NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 8
NDefines.NEconomy.TRADE_NON_CAPITAL_OFFICE = -0.25
NDefines.NEconomy.CARAVAN_POWER_MAX = 25
NDefines.NEconomy.CARAVAN_POWER_MIN = 1
NDefines.NEconomy.HEAVY_SHIP_MAINT_FACTOR = 0.08					-- _EDEF_HEAVY_SHIP_MAINT_FACTOR_
NDefines.NEconomy.LIGHT_SHIP_MAINT_FACTOR = 0.03					-- _EDEF_LIGHT_SHIP_MAINT_FACTOR_
NDefines.NEconomy.GALLEY_MAINT_FACTOR = 0.04					-- _EDEF_GALLEY_MAINT_FACTOR_
NDefines.NEconomy.TRANSPORT_MAINT_FACTOR = 0.02					-- _EDEF_TRANSPORT_MAINT_FACTOR_